### ISSUE TITLE
traj_conv gradcheck fail

### ISSUE THREAD

**Issue by TotallyFine** [open-mmlab/mmaction#10]
Successfully complie traj_conv but running mmaction/ops/trajectory_conv_package/gradcheck.py failed.
```
Traceback (most recent call last):
  File "gradcheck.py", line 27, in <module>
    test = gradcheck(conv_offset3d, (input, offset), eps=1e-5, atol=1e-1, rtol=1e-5)
  File "xxx/python3.6/site-packages/torch/autograd/gradcheck.py", line 214, in gradcheck
    'numerical:%s\nanalytical:%s\n' % (i, j, n, a))
  File "xxx/python3.6/site-packages/torch/autograd/gradcheck.py", line 194, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)
analytical:tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)
```

**Comment by zhaoyue-zephyrus** [comment]
Hi @TotallyFine ,

Thanks for raising this issue.

The trajectory convolution operator was originally written in Caffe and this is an adapted version from the updated [DCNv2](https://github.com/CharlesShang/DCNv2).

In our experiment, the results seems to be okay (I will shortly upload the TrajectoryNet's config part).

I still need some time to check this issue in details. You may refer to the DCNv2 repo for some exploration as well. Let's keep this issue open.

**Comment by anshulbshah** [comment]
Hi, do you have any updates on this ? Do you have an example configuration to use TrajConv ?
Thanks!
