### ISSUE TITLE
IndexError: dimension specified as 0 but tensor has no dimensions!

### ISSUE THREAD

**Issue by CrossStyle** [open-mmlab/mmaction#108]
(mmaction) zaolin@zaolin-H170M-D3H:~/mmaction$ python tools/train_recognizer.py /home/zaolin/mmaction/configs/ucf101/tsn_rgb_bninception.py 
2019-10-25 11:26:23,933 - INFO - Distributed training: False
2019-10-25 11:26:24,034 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2019-10-25 11:26:26,716 - INFO - Start running, host: zaolin@zaolin-H170M-D3H, work_dir: /home/zaolin/mmaction/work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8
2019-10-25 11:26:26,716 - INFO - workflow: [('train', 1)], max: 80 epochs
/pytorch/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
Traceback (most recent call last):
  File "tools/train_recognizer.py", line 84, in <module>
    main()
  File "tools/train_recognizer.py", line 80, in main
    train_network(model,train_dataset, cfg, distributed=distributed, validate=args.validate, logger=logger)
  File "/home/zaolin/mmaction/mmaction/apis/train.py", line 59, in train_network
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/zaolin/mmaction/mmaction/apis/train.py", line 127, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/zaolin/mmaction/mmaction/apis/train.py", line 36, in batch_processor
    losses = model(**data)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zaolin/mmaction/mmaction/models/recognizers/base.py", line 39, in forward
    return self.forward_train(num_modalities, img_meta, **kwargs)
  File "/home/zaolin/mmaction/mmaction/models/recognizers/TSN2D.py", line 128, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_label)
  File "/home/zaolin/mmaction/mmaction/models/tenons/cls_heads/cls_head.py", line 61, in loss
    losses['loss_cls'] = F.cross_entropy(cls_score, labels)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/zaolin/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/nn/functional.py", line 1834, in nll_loss
    if input.size(0) != target.size(0):
IndexError: dimension specified as 0 but tensor has no dimensions

**Comment by CrossStyle** [comment]
pytorch version 1.3.0
python 3.7
unbantu 18.04

**Comment by zhaoyue-zephyrus** [comment]
hi @CrossStyle 

Would you kindly first switch to PyTorch 1.0 or 1.1 to see if it works. For the time being I haven't checked pytorch 1.3 yet.

**Comment by CrossStyle** [comment]
@zhaoyue-zephyrus  I had switched to PyTorch 1.0.0, and it got the same problem.

**Comment by CrossStyle** [comment]
(action) zaolin@zaolin-H170M-D3H:~/下载/mmaction$ python tools/train_recognizer.py /home/zaolin/下载/mmaction/configs/ucf101/tsn_rgb_bninception.py --launcher none 
2019-10-25 18:30:40,281 - INFO - Distributed training: False
2019-10-25 18:30:41,136 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2019-10-25 18:30:51,170 - INFO - Start running, host: zaolin@zaolin-H170M-D3H, work_dir: /home/zaolin/下载/mmaction/work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8
2019-10-25 18:30:51,170 - INFO - workflow: [('train', 1)], max: 80 epochs
Traceback (most recent call last):
  File "tools/train_recognizer.py", line 84, in <module>
    main()
  File "tools/train_recognizer.py", line 80, in main
    train_network(model,train_dataset, cfg, distributed=distributed, validate=args.validate, logger=logger)
  File "/home/zaolin/下载/mmaction/mmaction/apis/train.py", line 59, in train_network
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/zaolin/下载/mmaction/mmaction/apis/train.py", line 127, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/zaolin/下载/mmaction/mmaction/apis/train.py", line 36, in batch_processor
    losses = model(**data)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zaolin/下载/mmaction/mmaction/models/recognizers/base.py", line 39, in forward
    return self.forward_train(num_modalities, img_meta, **kwargs)
  File "/home/zaolin/下载/mmaction/mmaction/models/recognizers/TSN2D.py", line 128, in forward_train
    loss_cls = self.cls_head.loss(cls_score, gt_label)
  File "/home/zaolin/下载/mmaction/mmaction/models/tenons/cls_heads/cls_head.py", line 61, in loss
    losses['loss_cls'] = F.cross_entropy(cls_score, labels)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/torch/nn/functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/zaolin/anaconda3/envs/action/lib/python3.5/site-packages/torch/nn/functional.py", line 1786, in nll_loss
    if input.size(0) != target.size(0):
RuntimeError: dimension specified as 0 but tensor has no dimensions

**Comment by CrossStyle** [comment]
@zhaoyue-zephyrus  I use my own data to train it with 1 GPU and turn off distributed training.

**Comment by zhaoyue-zephyrus** [comment]
I tried the same setting - one GPU without distributed training and got no error. Could you double check the version by 
```
import torch
print(torch.__version__)
```

**Comment by CrossStyle** [comment]
@zhaoyue-zephyrus (action) zaolin@zaolin-H170M-D3H:~$ python
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.0

**Comment by CrossStyle** [comment]
# model settings
model = dict(
    type='TSN2D',
    backbone=dict(
        type='BNInception',
        pretrained='open-mmlab://bninception_caffe',
        bn_eval=False,
        partial_bn=True),
    spatial_temporal_module=dict(
        type='SimpleSpatialModule',
        spatial_type='avg',
        spatial_size=7),
    segmental_consensus=dict(
        type='SimpleConsensus',
        consensus_type='avg'),
    cls_head=dict(
        type='ClsHead',
        with_avg_pool=False,
        temporal_feature_size=1,
        spatial_feature_size=1,
        dropout_ratio=0.8,
        in_channels=1024,
        init_std=0.001,
        num_classes=5))############101
train_cfg = None
test_cfg = None
# dataset settings
dataset_type = 'RawFramesDataset'
data_root = '/home/zaolin/mmaction/data/ucf101/rawframes'############绝对路径
img_norm_cfg = dict(
   mean=[104, 117, 128], std=[1, 1, 1], to_rgb=False)

data = dict(
    videos_per_gpu=1,#######32
    workers_per_gpu=1,#######2
    train=dict(
        type=dataset_type,
        ann_file='/home/zaolin/mmaction/data/ucf101/ucf101_train_split_1_rawframes.txt',
        img_prefix=data_root,
        img_norm_cfg=img_norm_cfg,
        num_segments=3,
        new_length=1,
        new_step=1,
        random_shift=True,
        modality='RGB',
        image_tmpl='img_{:05d}.jpg',
        img_scale=256,
        input_size=224,
        div_255=False,
        flip_ratio=0.5,
        resize_keep_ratio=True,
        oversample=None,
        random_crop=False,
        more_fix_crop=False,
        multiscale_crop=True,
        scales=[1, 0.875, 0.75, 0.66],
        max_distort=1,
        test_mode=False),
    val=dict(
        type=dataset_type,
        ann_file='/home/zaolin/mmaction/data/ucf101/ucf101_val_split_1_rawframes.txt',
        img_prefix=data_root,
        img_norm_cfg=img_norm_cfg,
        num_segments=3,
        new_length=1,
        new_step=1,
        random_shift=False,
        modality='RGB',
        image_tmpl='img_{:05d}.jpg',
        img_scale=256,
        input_size=224,
        div_255=False,
        flip_ratio=0,
        resize_keep_ratio=True,
        oversample=None,
        random_crop=False,
        more_fix_crop=False,
        multiscale_crop=False,
        test_mode=False),
    test=dict(
        type=dataset_type,
        ann_file='/home/zaolin/mmaction/data/ucf101/ucf101_val_split_1_rawframes.txt',
        img_prefix=data_root,
        img_norm_cfg=img_norm_cfg,
        num_segments=25,
        new_length=1,
        new_step=1,
        random_shift=False,
        modality='RGB',
        image_tmpl='img_{:05d}.jpg',
        img_scale=256,
        input_size=224,
        div_255=False,
        flip_ratio=0,
        resize_keep_ratio=True,
        oversample='ten_crop',
        random_crop=False,
        more_fix_crop=False,
        multiscale_crop=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    step=[30, 60])
checkpoint_config = dict(interval=1)
# workflow = [('train', 5), ('val', 1)]
workflow = [('train', 1)]
# yapf:disable
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 80
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8'
load_from = None
resume_from = None

**Comment by CrossStyle** [comment]
from __future__ import division

import argparse
from mmcv import Config

from mmaction import __version__
from mmaction.datasets import get_trimmed_dataset
from mmaction.apis import (train_network, init_dist, get_root_logger,
                           set_random_seed)
from mmaction.models import build_recognizer
import torch


def parse_args():
    parser = argparse.ArgumentParser(description='Train an action recognizer')
    parser.add_argument('config', help='train config file path')
    parser.add_argument('--work_dir', help='the dir to save logs and models')
    parser.add_argument(
        '--resume_from', help='the checkpoint file to resume from')
    parser.add_argument(
        '--validate',
        action='store_true',
        help='whether to evaluate the checkpoint during training')
    parser.add_argument(
        '--gpus',
        type=int,
        default=1,
        help='number of gpus to use '
        '(only applicable to non-distributed training)')
    parser.add_argument('--seed', type=int, default=None, help='random seed')
    parser.add_argument(
        '--launcher',
        choices=['none', 'pytorch', 'slurm', 'mpi'],
        default='none',
        help='job launcher')
    parser.add_argument('--local_rank', type=int, default=0)
    args = parser.parse_args()

    return args


def main():
    args = parse_args()

    cfg = Config.fromfile(args.config)
    # set cudnn_benchmark
    if cfg.get('cudnn_benchmark', False):
        torch.backends.cudnn.benchmark = True
    # update configs according to CLI args
    if args.work_dir is not None:
        cfg.work_dir = args.work_dir
    if args.resume_from is not None:
        cfg.resume_from = args.resume_from
    cfg.gpus = args.gpus
    if cfg.checkpoint_config is not None:
        # save mmaction version in checkpoints as meta data
        cfg.checkpoint_config.meta = dict(
            mmact_version=__version__, config=cfg.text)

    # init distributed env first, since logger depends on the dist info.
    if args.launcher == 'none':
        distributed = False
    else:
        distributed = True
        init_dist(args.launcher, **cfg.dist_params)

    # init logger before other steps
    logger = get_root_logger(cfg.log_level)
    logger.info('Distributed training: {}'.format(distributed))

    # set random seeds
    if args.seed is not None:
        logger.info('Set random seed to {}'.format(args.seed))
        set_random_seed(args.seed)

    model = build_recognizer(
        cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)

    train_dataset = get_trimmed_dataset(cfg.data.train)
    train_network(model,train_dataset, cfg, distributed=distributed, validate=args.validate, logger=logger)


if __name__ == '__main__':
    main()

**Comment by CrossStyle** [comment]
@zhaoyue-zephyrus That's my config setting (tsn_rgb_bninception.py) and train_recognizer.py.Is it wrong with the feature extraction process of my data?

**Comment by zhaoyue-zephyrus** [comment]
`videos_per_gpu=1` caused the problem. Change it to any integer greater than 1.

**Comment by CrossStyle** [comment]
@zhaoyue-zephyrus  It works! Thank you so much for helping me!
