### ISSUE TITLE
List index out of range in Kinetics testing

### ISSUE THREAD

**Issue by volpepe** [open-mmlab/mmaction#133]
Hi,
I downloaded Kinetics (validation split only) with the provided crawler and since I also had problems with decord and raw video testing, I extracted the rgb rawframes.
I tested both one of the provided SlowOnly model and the i3d model with the following commands:
```
tools/dist_test_recognizer.sh configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py /home/frameworks/mmaction/modelzoo/i3d_kinetics_rgb_r50_c3d_inflated3x1x1_seg1_f32s2_f32s2-b93cc877.pth 2
```
for i3d and
```
tools/dist_test_recognizer.sh configs/kinetics400/slowonly_kinetics400_se_rgb_r50_seg1_8x8_finetune.py modelzoo/slowonly_kinetics400_se_rgb_r50_seg1_8x8_finetune_epoch150-519c2101.pth 2 
```
since I'm using the code on a computer with 2 TitanX GPUs. Also, I'm using your provided docker image to do these tests.
I get the same error for both of the tests. This is my output:
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

rank 1, data_batch 0
rank 0, data_batch 0
Traceback (most recent call last):
  File "tools/test_recognizer.py", line 182, in <module>
    main()
  File "tools/test_recognizer.py", line 156, in main
    outputs = multi_test(model, data_loader)
  File "tools/test_recognizer.py", line 35, in multi_test
    for i, data in enumerate(data_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.5/dist-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/mmaction/mmaction/datasets/rawframes_dataset.py", line 275, in __getitem__
    gt_label=DC(to_tensor(record.label), stack=True,
  File "/data/mmaction/mmaction/datasets/rawframes_dataset.py", line 25, in label
    return int(self._data[2])
IndexError: list index out of range
```
Can you help me fixing this? I already successfully used dist_test_recognizer.py for testing TSN on the three UCF101 splits, so I was really expecting this to work.
Thanks.

**Comment by volpepe** [comment]
I fixed this. Apparently some of the videos in Kinetics were written into the file without a number, so I made a script to remove those videos from the validation set.
