### ISSUE TITLE
KeyError: 'RANK'

### ISSUE THREAD

**Issue by xueyingliu** [open-mmlab/mmaction#181]
when I run **tools/test_recognizer_heavy.py** file, I get the following error:
```
Traceback (most recent call last):
  File "tools/test_recognizer_heavy.py", line 211, in <module>
    main()
  File "tools/test_recognizer_heavy.py", line 170, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/media/liuxy/dataset/mmaction/mmaction/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/media/liuxy/dataset/mmaction/mmaction/apis/env.py", line 27, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/usr/local/src/python37/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```
Can anyone give me some idea to solve this? Thanks!

**Comment by Ffmydy** [comment]
i have the same question ,how to solve it?

**Comment by V2KO-pge** [comment]
Did anyone find any solution to this?
