### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by YanjunChen** [open-mmlab/mmaction#195]
could you please help me with this problem？
I got this error when I install the mmaction while running  `./compile.sh`
THX

`Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 437, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/user/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
`

**Comment by 1299372364** [comment]
Hello, I have the same question. Could you tell me if you have sovled it?
