### ISSUE TITLE
RuntimeError: Given input size: (1024x6x7). Calculated output size: (1024x0x1). Output size is too small

### ISSUE THREAD

**Issue by qintao361** [open-mmlab/mmaction#197]
when i try to run the test_localizer.py with command:
`python tools/test_localizer.py test_configs/thumos14/ssn_thumos14_rgb_bn_inception.py modelzoo/ssn_thumos14_rgb_bn_inception_tag-dac9ddb0.pth --out ./output/result.pkl --eval thumos14`

the error occurs, like"
`Traceback (most recent call last):
  File "/home/user/pose/mmaction/tools/test_localizer.py", line 179, in <module>
    main()
  File "/home/user/pose/mmaction/tools/test_localizer.py", line 107, in main
    outputs = single_test(model, data_loader)
  File "/home/user/pose/mmaction/tools/test_localizer.py", line 30, in single_test
    result = model(return_loss=False, **data)
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/pose/mmaction/mmaction/models/localizers/base.py", line 32, in forward
    return self.forward_test(num_modalities, img_meta, **kwargs)
  File "/home/user/pose/mmaction/mmaction/models/localizers/SSN2D.py", line 169, in forward_test
    x = self.spatial_temporal_module(x)
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/pose/mmaction/mmaction/models/tenons/spatial_temporal_modules/simple_spatial_module.py", line 25, in forward
    return self.op(input)
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/pose/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (1024x6x7). Calculated output size: (1024x0x1). Output size is too small`
@yjxiong could you help check what's happened? thanks a lot.

**Comment by kennymckormick** [comment]
Hi, that problem is due to the image size of your THUMOS14 data, in ssn config we resize it to (340, 256) with `resize_keep_ratio=True`, so that maybe after resizing the short edge will be less than 224px. We have updated the config of ssn, to resize images to 256(short edge). You can try our new code, the problem should have been solved.

**Comment by qintao361** [comment]
@kennymckormick it works...thanks a lot!
