### ISSUE TITLE
errors in training with video type

### ISSUE THREAD

**Issue by LiuChaoXD** [open-mmlab/mmaction#203]
I install the mmcv library with the step for the GitHub.
When I train the tsn model with ucf101 dataset (video type), the errors will be randomly occurred~
For example, I run 
```
maction) root@bjyz-sys-gpu-kongming4:/ssd8/liuchao45/mmaction#  ./tools/dist_train_recognizer.sh ./configs/TSN/ucf101/tsn_video_resnet50.py 4 --validate*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2020-08-04 16:21:08,131 - INFO - Distributed training: True
2020-08-04 16:21:14,965 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
2020-08-04 16:21:15,067 - INFO - Start running, host: root@bjyz-sys-gpu-kongming4.bjyz.baidu.com, work_dir: /ssd8/liuchao45/mmaction/work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8
2020-08-04 16:21:15,068 - INFO - workflow: [('train', 1)], max: 80 epochs
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
2020-08-04 16:21:54,034 - INFO - Epoch [1][20/75]       lr: 1.000e-03, eta: 3:14:10, time: 1.948, data_time: 0.615, memory: 8331, loss_cls: 4.7250, loss: 4.7250
2020-08-04 16:22:24,059 - INFO - Epoch [1][40/75]       lr: 1.000e-03, eta: 2:51:19, time: 1.501, data_time: 0.043, memory: 8331, loss_cls: 4.6696, loss: 4.6696
2020-08-04 16:22:54,177 - INFO - Epoch [1][60/75]       lr: 1.000e-03, eta: 2:43:29, time: 1.505, data_time: 0.043, memory: 8331, loss_cls: 4.5525, loss: 4.5525
2020-08-04 16:23:15,935 - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3784/3783, 64.5 task/s, elapsed: 59s, ETA:     0s

2020-08-04 16:24:15,421 - INFO - Epoch(val) [0][75]     top1 acc: 0.1449, top5 acc: 0.3241
2020-08-04 16:24:52,505 - INFO - Epoch [2][20/75]       lr: 1.000e-03, eta: 2:21:01, time: 1.852, data_time: 0.957, memory: 8331, loss_cls: 4.3984, loss: 4.3984
2020-08-04 16:25:22,320 - INFO - Epoch [2][40/75]       lr: 1.000e-03, eta: 2:21:32, time: 1.491, data_time: 0.498, memory: 8331, loss_cls: 4.3143, loss: 4.3143
2020-08-04 16:25:51,026 - INFO - Epoch [2][60/75]       lr: 1.000e-03, eta: 2:20:57, time: 1.436, data_time: 0.662, memory: 8331, loss_cls: 4.2282, loss: 4.2282
Traceback (most recent call last):
  File "./tools/train_recognizer.py", line 90, in <module>
    main()
  File "./tools/train_recognizer.py", line 86, in main
    logger=logger)
  File "/ssd8/liuchao45/mmaction/mmaction/apis/train.py", line 58, in train_network
    _dist_train(model, dataset, cfg, logger, validate=validate)
  File "/ssd8/liuchao45/mmaction/mmaction/apis/train.py", line 101, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/video_dataset.py", line 344, in __getitem__
    is_flow=True if modality == 'Flow' else False)
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/transforms.py", line 430, in __call__
    img, scale, return_scale=True) for img in img_group]
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/transforms.py", line 430, in <listcomp>
    img, scale, return_scale=True) for img in img_group]
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/image/geometric.py", line 175, in imrescale
    h, w = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```
The errors will be occurred in the second training epoch. However, when I run this same command the error will be occurred in the first validating epoch, like the following shows:
```

(mmaction) root@bjyz-sys-gpu-kongming4:/ssd8/liuchao45/mmaction# ./tools/dist_train_recognizer.sh ./configs/TSN/ucf101/tsn_video_resnet50.py 4 --validate   
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2020-08-04 16:03:04,410 - INFO - Distributed training: True
2020-08-04 16:03:11,293 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
2020-08-04 16:03:11,399 - INFO - Start running, host: root@bjyz-sys-gpu-kongming4.bjyz.baidu.com, work_dir: /ssd8/liuchao45/mmaction/work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8
2020-08-04 16:03:11,399 - INFO - workflow: [('train', 1)], max: 80 epochs
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
2020-08-04 16:03:49,440 - INFO - Epoch [1][20/75]	lr: 1.000e-03, eta: 3:09:33, time: 1.902, data_time: 0.473, memory: 8331, loss_cls: 4.7290, loss: 4.7290
2020-08-04 16:04:19,402 - INFO - Epoch [1][40/75]	lr: 1.000e-03, eta: 2:48:51, time: 1.498, data_time: 0.042, memory: 8331, loss_cls: 4.6813, loss: 4.6813
2020-08-04 16:04:49,276 - INFO - Epoch [1][60/75]	lr: 1.000e-03, eta: 2:41:26, time: 1.492, data_time: 0.043, memory: 8331, loss_cls: 4.5779, loss: 4.5779
2020-08-04 16:05:12,650 - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3784/3783, 59.4 task/s, elapsed: 64s, ETA:     0s

2020-08-04 16:06:18,581 - INFO - Epoch(val) [0][75]	top1 acc: 0.1438, top5 acc: 0.3315
Traceback (most recent call last):
  File "./tools/train_recognizer.py", line 90, in <module>
    main()
  File "./tools/train_recognizer.py", line 86, in main
    logger=logger)
  File "/ssd8/liuchao45/mmaction/mmaction/apis/train.py", line 58, in train_network
    _dist_train(model, dataset, cfg, logger, validate=validate)
  File "/ssd8/liuchao45/mmaction/mmaction/apis/train.py", line 101, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/mmaction/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/video_dataset.py", line 344, in __getitem__
    is_flow=True if modality == 'Flow' else False)
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/transforms.py", line 430, in __call__
    img, scale, return_scale=True) for img in img_group]
  File "/ssd8/liuchao45/mmaction/mmaction/datasets/transforms.py", line 430, in <listcomp>
    img, scale, return_scale=True) for img in img_group]
  File "/ssd8/liuchao45/mmaction/mmcv/mmcv/image/geometric.py", line 175, in imrescale
    h, w = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by LiuChaoXD** [comment]
This is my packages in the mmaction environment

```
(mmaction) root@bjyz-sys-gpu-kongming4:/ssd8/liuchao45/mmaction# conda list
# packages in environment at /root/anaconda3/envs/mmaction:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
addict                    2.2.1                    pypi_0    pypi
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py37_0  
cudatoolkit               9.2                           0  
cython                    0.29.21                  pypi_0    pypi
joblib                    0.16.0                   pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
lmdb                      0.98                     pypi_0    pypi
mmaction                  0.1rc0+b5487ab            dev_0    <develop>
mmcv-full                 1.0.5                     dev_0    <develop>
ncurses                   6.2                  he6710b0_1  
numpy                     1.19.1                   pypi_0    pypi
opencv-python             4.3.0.36                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
pillow                    7.2.0                    pypi_0    pypi
pip                       20.1.1                   py37_1  
python                    3.7.7                hcff3b4d_5  
readline                  8.0                  h7b6447c_0  
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
setuptools                49.2.0                   py37_0  
six                       1.15.0                   pypi_0    pypi
sqlite                    3.32.3               h62c20be_0  
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.3.0+cu92               pypi_0    pypi
torchvision               0.4.1+cu92               pypi_0    pypi
wheel                     0.34.2                   py37_0  
xz                        5.2.5                h7b6447c_0  
yapf                      0.30.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3
```

**Comment by zhaoyue-zephyrus** [comment]
Hi @LiuChaoXD 

The error indicates that the img is a `None` which means the video decoder fails to fetch the frame correctly. It is probably caused by `mmcv.VideoReader`. Please try consider using `decord` (build from master branch).

**Comment by sjeevanandam** [comment]
@LiuChaoXD I have been having the same issue. Did you solve this? If so can you please let me know as well.

**Comment by zhaoyue-zephyrus** [comment]
@sjeevanandam please check that *every* one of your video can be loaded successfully. (You may run a quick script for sanity check.)  As mentioned in my previous comment, this error occurs when the video decoder fails to fetch frames correctly.
