### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pad_dims'

### ISSUE THREAD

**Issue by huiyang865** [open-mmlab/mmaction#21]
when I run the command './tools/dist_train_detector.sh configs/ava/ava_fast_rcnn_nl_r50_c4_1x_kinetics_pretrain_crop.py 4' for the spatial-temporal action detection model, an error appears:
```
Traceback (most recent call last):
  File "./tools/train_detector.py", line 90, in <module>
    main()
  File "./tools/train_detector.py", line 86, in main
    logger=logger)
  File "/yanghui_root/mmaction/mmaction/apis/train.py", line 57, in train_network
    _dist_train(model, dataset, cfg, validate=validate)
  File "/yanghui_root/mmaction/mmaction/apis/train.py", line 102, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 258, in train
    for i, data_batch in enumerate(data_loader):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 583, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 609, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 108, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 108, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/yanghui_root/mmaction/mmaction/datasets/ava_dataset.py", line 348, in __getitem__
    data = self.prepare_train_imgs(idx)
  File "/yanghui_root/mmaction/mmaction/datasets/ava_dataset.py", line 434, in prepare_train_imgs
    img_group_0=DC(to_tensor(img_group), stack=True, pad_dims=2),
TypeError: __init__() got an unexpected keyword argument 'pad_dims'
```

My mmcv version is mmcv-0.2.8.

**Comment by zhaoyue-zephyrus** [comment]
@huiyang865  

Could you please install mmcv by cloning the master branch and install it from scratch? MMAction requires several new features (such as more flexible DataContainer and new pre-trained models) of mmcv, which haven't been included in the latest release.

**Comment by huiyang865** [comment]
Thanks for your reply. It's OK with the mmcv installed from scratch.
