### ISSUE TITLE
KeyError: 'TSN2D is not in the detector registry'

### ISSUE THREAD

**Issue by camCX** [open-mmlab/mmaction#220]
Hi,

Sorry to be a bother.But I need your help.

I successfully installed the requirements. But when I use `python ./tools/train_detector.py configs/TSN/ucf101/tsn_flow_bninception.py`  to train a model with a single GPU, I got an error message:

`~/mmaction$ python ./tools/train_detector.py configs/TSN/ucf101/tsn_flow_bninception.py 
2020-11-11 23:22:14,572 - INFO - Distributed training: False
Traceback (most recent call last):
  File "./tools/train_detector.py", line 90, in <module>
    main()
  File "./tools/train_detector.py", line 77, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/cam/camcode/mmaction/mmaction/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/cam/camcode/mmaction/mmaction/models/builder.py", line 34, in build
    return _build_module(cfg, registry, default_args)
  File "/home/cam/camcode/mmaction/mmaction/models/builder.py", line 18, in _build_module
    obj_type, registry.name))
KeyError: 'TSN2D is not in the detector registry'`

Here is my environment ：

Ubuntu 18.04,

V100,

GCC 7.5,

CUDA10.0,

Pytorch 1.7.0

mmcv 1.0.3

python 3.6.9

Thanks！

**Comment by kennymckormick** [comment]
Hi, camCX,
    `configs/TSN/ucf101/tsn_flow_bninception.py` is not a detector but a recognizer, plz run `python tools/train_recognizer.py` instead
