### ISSUE TITLE
error while Install MMAction

### ISSUE THREAD

**Issue by isalirezag** [open-mmlab/mmaction#31]
Hopefully this is my last error in the installation part :/
So I am trying to do Install MMAction.
when i run `./compile.sh` it gives me:
`bash: ./compile.sh: Permission denied`

so i did `sudo bash compile.sh`

but then I got 
```
Building package resample2d
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import torch
ImportError: No module named torch
Building package trajectory_conv...
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import torch
ImportError: No module named torch
Building roi align op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building roi pool op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building nms op...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
alireza@alireza:~/Desktop/mmaction$ 

```

I think the problem is that i have python 3.6 via using anaconda, but it cannot find that path.
because all the packages that it says i dont have i do have them.

```
alireza@alireza:~/Desktop/mmaction$ which python
/home/alireza/anaconda3/bin/python
alireza@alireza:~/Desktop/mmaction$ which cython
/home/alireza/anaconda3/bin/cython
```

can you please help me to make it to look at the right path. I think something is compile.sh should change but not sure what.

Thanks

**Comment by zhaoyue-zephyrus** [comment]
Please don't do it `sudo`. Could you please just do `bash compile.sh`?

**Comment by immaping** [comment]
I have the same issue,could you tell me how do you solve it?
