### ISSUE TITLE
temporal action detection

### ISSUE THREAD

**Issue by isalirezag** [open-mmlab/mmaction#35]
I like to do temporal action detection.
Can you help on how to evaluated the existing methods on THUMOS14 dataset

**Comment by isalirezag** [comment]
do i need to have optical flow frames for this evaluation?

**Comment by isalirezag** [comment]
I run the code as 
`python tools/test_localizer.py configs/thumos14/ssn_thumos14_rgb_bn_inception.py modelzoo/ssn_thumos14_rgb_bn_inception_tag-dac9ddb0.pth --gpus 1 --out ssn_thumos14_rgb_bn_inception_AlirezaTest.pkl --eval thumos14`
and received this error:

```
data/thumos14/thumos14_tag_test_proposal_list.txt
210 out of 1574 videos are valid.

            SSNDataset: proposal file data/thumos14/thumos14_tag_test_proposal_list.txt parsed.
            
Traceback (most recent call last):
  File "tools/test_localizer.py", line 178, in <module>
    main()
  File "tools/test_localizer.py", line 95, in main
    cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/home/alireza/Desktop/mmaction/mmaction/models/builder.py", line 63, in build_localizer
    return build(cfg, LOCALIZERS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/alireza/Desktop/mmaction/mmaction/models/builder.py", line 34, in build
    return _build_module(cfg, registry, default_args)
  File "/home/alireza/Desktop/mmaction/mmaction/models/builder.py", line 26, in _build_module
    return obj_type(**args)
  File "/home/alireza/Desktop/mmaction/mmaction/models/localizers/SSN2D.py", line 54, in __init__
    self.init_weights()
  File "/home/alireza/Desktop/mmaction/mmaction/models/localizers/SSN2D.py", line 99, in init_weights
    self.backbone.init_weights()
  File "/home/alireza/Desktop/mmaction/mmaction/models/tenons/backbones/bninception.py", line 253, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/home/alireza/anaconda3/lib/python3.6/site-packages/mmcv-0.2.8-py3.6.egg/mmcv/runner/checkpoint.py", line 120, in load_checkpoint
    checkpoint = model_zoo.load_url(open_mmlab_model_urls[model_name])
KeyError: 'bninception_caffe'
alireza@alireza:~/Desktop/mmaction$ 

```

**Comment by zhaoyue-zephyrus** [comment]
@isalirezag 
Looking at the error,  it seems like the input size is too small. Could you check that?

**Comment by isalirezag** [comment]
hmmm can you please tell where should i change it, i didnot change any part of the code.
should I define input size somewhere?

**Comment by zhaoyue-zephyrus** [comment]
I tried running the code and there is no problem.

In addition, the input size has been defined in the config: https://github.com/open-mmlab/mmaction/blob/master/configs/thumos14/ssn_thumos14_rgb_bn_inception.py#L82, therefore the input will be resize to 340x256 and a 224x224 crop will be obtain thereon. 

Maybe you have to check you input, for example are all of them successfully extracted?

**Comment by smilefish06** [comment]
I also met the same problem. I just wonder whether it's caused the un-matched configuration since I only have two GPUs.

**Comment by smilefish06** [comment]
I met the same problem. "RuntimeError: Given input size: (1024x6x7). Calculated output size: (1024x0x1). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:47
". The input is from x = self.extract_feat(chunk.cuda()) in SSN2D.py

**Comment by zhaoyue-zephyrus** [comment]
Please refer to #63 for details.
