### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pad_dims'

### ISSUE THREAD

**Issue by yyf8989** [open-mmlab/mmaction#37]
shichen@shichen-Inspiron-3670:~/mma/mmaction$ python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 
[                                                  ] 0/38, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test_recognizer.py", line 122, in <module>
    main()
  File "tools/test_recognizer.py", line 83, in main
    outputs = single_test(model, data_loader)
  File "tools/test_recognizer.py", line 20, in single_test
    for i, data in enumerate(data_loader):
  File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/shichen/mmaction-master/mmaction/datasets/rawframes_dataset.py", line 272, in __getitem__
    pad_dims=None))
TypeError: __init__() got an unexpected keyword argument 'pad_dims'

Hi, thank you for your code.

when I ran 'python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth' showed as Getting_start.md, it shows that error I pasted.

I have checked that function and there is no attributes 'pad_dims'.
Is that a bug?

Thank you. @zhaoyue-zephyrus

**Comment by yyf8989** [comment]
> shichen@shichen-Inspiron-3670:~/mma/mmaction$ python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth
> [ ] 0/38, elapsed: 0s, ETA:Traceback (most recent call last):
> File "tools/test_recognizer.py", line 122, in 
> main()
> File "tools/test_recognizer.py", line 83, in main
> outputs = single_test(model, data_loader)
> File "tools/test_recognizer.py", line 20, in single_test
> for i, data in enumerate(data_loader):
> File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in **next**
> return self._process_next_batch(batch)
> File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> TypeError: Traceback (most recent call last):
> File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/shichen/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in 
> samples = collate_fn([dataset[i] for i in batch_indices])
> File "/home/shichen/mmaction-master/mmaction/datasets/rawframes_dataset.py", line 272, in **getitem**
> pad_dims=None))
> TypeError: **init**() got an unexpected keyword argument 'pad_dims'
> 
> Hi, thank you for your code.
> 
> when I ran 'python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth' showed as Getting_start.md, it shows that error I pasted.
> 
> I have checked that function and there is no attributes 'pad_dims'.
> Is that a bug?
> 
> Thank you.
