### ISSUE TITLE
Mistake when apply parallel test

### ISSUE THREAD

**Issue by liya2001** [open-mmlab/mmaction#51]
I tried to apply parallel test but this error occurred:
_pickle.PicklingError: Can't pickle <function _data_func at 0x7fe56fa76510>: attribute lookup _data_func on __main__ failed
@zhaoyue-zephyrus

**Comment by zhaoyue-zephyrus** [comment]
@liya2001 Sorry for replying late.

1. Which command do you execute?

2. Do you have complete error log? (Remember to quote them to avoid issue reference)

**Comment by liya2001** [comment]
The command 

> CUDA_VISIBLE_DEVICES=1,2 python tools/test_localizer.py ${CONFIG_FILE} ${CHECKPOINT_FILE} --out ${RESULT_FILE}  --eval activitynet --gpus 2

The error log

> Traceback (most recent call last):
  File "tools/test_localizer.py", line 215, in <module>
    main()
  File "tools/test_localizer.py", line 151, in main
    workers_per_gpu=args.proc_per_gpu)
  File "/data00/home/liya/anaconda3/lib/python3.6/site-packages/mmcv/runner/parallel_test.py", line 59, in parallel_test
    w.start()
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/data00/home/liya/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function _data_func at 0x7fe7655f0378>: attribute lookup _data_func on __main__ failed

Thanks @zhaoyue-zephyrus
