### ISSUE TITLE
unexpected key in source state_dict

### ISSUE THREAD

**Issue by HaiyiMei** [open-mmlab/mmaction#53]
When I wanna test i3d model in kinetics dataset with the pretrained model you offered in Model zoo, these series of "unexpected key" problem occurred.

```shell
~/Downloads/mmaction$ python tools/test_recognizer.py configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py modelzoo/i3d_r50_f32s2_k400-2c57e077.pth

unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer3.0.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.2.bn1.num_batches_tracked

Traceback (most recent call last):
  File "tools/test_recognizer.py", line 123, in <module>
    main()
  File "tools/test_recognizer.py", line 74, in main
    load_checkpoint(model, args.checkpoint, strict=True)
  File "/home/fourier/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 162, in load_checkpoint
    load_state_dict(model, state_dict, strict, logger)
  File "/home/fourier/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 86, in load_state_dict
    raise RuntimeError(err_msg)
RuntimeError: unexpected key in source state_dict: conv1.weight, bn1.weight, bn1.bias, bn1.running_mean, bn1.running_var, bn1.num_batches_tracked, layer1.0.conv1.weight, layer1.0.conv2.weight, layer1.0.bn1.weight, layer1.0.bn1.bias, layer1.0.bn1.running_mean, layer1.0.bn1.running_var, layer1.0.bn1.num_batches_tracked, layer1.0.bn2.weight, layer1.0.bn2.bias, layer1.0.bn2.running_mean, layer1.0.bn2.running_var, layer1.0.bn2.num_batches_tracked, layer1.0.conv3.weight, layer1.0.bn3.weight, layer1.0.bn3.bias, layer1.0.bn3.running_mean, layer1.0.bn3.running_var, layer1.0.bn3.num_batches_tracked, layer1.0.downsample.0.weight, layer1.0.downsample.1.weight, layer1.0.downsample.1.bias, layer1.0.downsample.1.running_mean, layer1.0.downsample.1.running_var, layer1.0.downsample.1.num_batches_tracked, layer1.1.conv1.weight, layer1.1.conv2.weight, layer1.1.bn1.weight, layer1.1.bn1.bias, layer1.1.bn1.running_mean, layer1.1.bn1.running_var, layer1.1.bn1.num_batches_tracked, layer1.1.bn2.weight, layer1.1.bn2.bias, layer1.1.bn2.running_mean, layer1.1.bn2.running_var, layer1.1.bn2.num_batches_tracked, layer1.1.conv3.weight, layer1.1.bn3.weight, layer1.1.bn3.bias, layer1.1.bn3.running_mean, layer1.1.bn3.running_var, layer1.1.bn3.num_batches_tracked, layer1.2.conv1.weight, layer1.2.conv2.weight, layer1.2.bn1.weight, layer1.2.bn1.bias, layer1.2.bn1.running_mean, layer1.2.bn1.running_var, layer1.2.bn1.num_batches_tracked, layer1.2.bn2.weight, layer1.2.bn2.bias, layer1.2.bn2.running_mean, layer1.2.bn2.running_var, layer1.2.bn2.num_batches_tracked, layer1.2.conv3.weight, layer1.2.bn3.weight, layer1.2.bn3.bias, layer1.2.bn3.running_mean, layer1.2.bn3.running_var, layer1.2.bn3.num_batches_tracked, layer2.0.conv1.weight, layer2.0.conv2.weight, layer2.0.bn1.weight, layer2.0.bn1.bias, layer2.0.bn1.running_mean, layer2.0.bn1.running_var, layer2.0.bn1.num_batches_tracked, layer2.0.bn2.weight, layer2.0.bn2.bias, layer2.0.bn2.running_mean, layer2.0.bn2.running_var, layer2.0.bn2.num_batches_tracked, layer2.0.conv3.weight, layer2.0.bn3.weight, layer2.0.bn3.bias, layer2.0.bn3.running_mean, layer2.0.bn3.running_var, layer2.0.bn3.num_batches_tracked, layer2.0.downsample.0.weight, layer2.0.downsample.1.weight, layer2.0.downsample.1.bias, layer2.0.downsample.1.running_mean, layer2.0.downsample.1.running_var, layer2.0.downsample.1.num_batches_tracked, layer2.1.conv1.weight, layer2.1.conv2.weight, layer2.1.bn1.weight, layer2.1.bn1.bias, layer2.1.bn1.running_mean, layer2.1.bn1.running_var, layer2.1.bn1.num_batches_tracked, layer2.1.bn2.weight, layer2.1.bn2.bias, layer2.1.bn2.running_mean, layer2.1.bn2.running_var, layer2.1.bn2.num_batches_tracked, layer2.1.conv3.weight, layer2.1.bn3.weight, layer2.1.bn3.bias, layer2.1.bn3.running_mean, layer2.1.bn3.running_var, layer2.1.bn3.num_batches_tracked, layer2.2.conv1.weight, layer2.2.conv2.weight, layer2.2.bn1.weight, layer2.2.bn1.bias, layer2.2.bn1.running_mean, layer2.2.bn1.running_var, layer2.2.bn1.num_batches_tracked, layer2.2.bn2.weight, layer2.2.bn2.bias, layer2.2.bn2.running_mean, layer2.2.bn2.running_var, layer2.2.bn2.num_batches_tracked, layer2.2.conv3.weight, layer2.2.bn3.weight, layer2.2.bn3.bias, layer2.2.bn3.running_mean, layer2.2.bn3.running_var, layer2.2.bn3.num_batches_tracked, layer2.3.conv1.weight, layer2.3.conv2.weight, layer2.3.bn1.weight, layer2.3.bn1.bias, layer2.3.bn1.running_mean, layer2.3.bn1.running_var, layer2.3.bn1.num_batches_tracked, layer2.3.bn2.weight, layer2.3.bn2.bias, layer2.3.bn2.running_mean, layer2.3.bn2.running_var, layer2.3.bn2.num_batches_tracked, layer2.3.conv3.weight, layer2.3.bn3.weight, layer2.3.bn3.bias, layer2.3.bn3.running_mean, layer2.3.bn3.running_var, layer2.3.bn3.num_batches_tracked, layer3.0.conv1.weight, layer3.0.conv2.weight, layer3.0.bn1.weight, layer3.0.bn1.bias, layer3.0.bn1.running_mean, layer3.0.bn1.running_var, layer3.0.bn1.num_batches_tracked, layer3.0.bn2.weight, layer3.0.bn2.bias, layer3.0.bn2.running_mean, layer3.0.bn2.running_var, layer3.0.bn2.num_batches_tracked, layer3.0.conv3.weight, layer3.0.bn3.weight, layer3.0.bn3.bias, layer3.0.bn3.running_mean, layer3.0.bn3.running_var, layer3.0.bn3.num_batches_tracked, layer3.0.downsample.0.weight, layer3.0.downsample.1.weight, layer3.0.downsample.1.bias, layer3.0.downsample.1.running_mean, layer3.0.downsample.1.running_var, layer3.0.downsample.1.num_batches_tracked, layer3.1.conv1.weight, layer3.1.conv2.weight, layer3.1.bn1.weight, layer3.1.bn1.bias, layer3.1.bn1.running_mean, layer3.1.bn1.running_var, layer3.1.bn1.num_batches_tracked, layer3.1.bn2.weight, layer3.1.bn2.bias, layer3.1.bn2.running_mean, layer3.1.bn2.running_var, layer3.1.bn2.num_batches_tracked, layer3.1.conv3.weight, layer3.1.bn3.weight, layer3.1.bn3.bias, layer3.1.bn3.running_mean, layer3.1.bn3.running_var, layer3.1.bn3.num_batches_tracked, layer3.2.conv1.weight, layer3.2.conv2.weight, layer3.2.bn1.weight, layer3.2.bn1.bias, layer3.2.bn1.running_mean, layer3.2.bn1.running_var, layer3.2.bn1.num_batches_tracked, layer3.2.bn2.weight, layer3.2.bn2.bias, layer3.2.bn2.running_mean, layer3.2.bn2.running_var, layer3.2.bn2.num_batches_tracked, layer3.2.conv3.weight, layer3.2.bn3.weight, layer3.2.bn3.bias, layer3.2.bn3.running_mean, layer3.2.bn3.running_var, layer3.2.bn3.num_batches_tracked, layer3.3.conv1.weight, layer3.3.conv2.weight, layer3.3.bn1.weight, layer3.3.bn1.bias, layer3.3.bn1.running_mean, layer3.3.bn1.running_var, layer3.3.bn1.num_batches_tracked, layer3.3.bn2.weight, layer3.3.bn2.bias, layer3.3.bn2.running_mean, layer3.3.bn2.running_var, layer3.3.bn2.num_batches_tracked, layer3.3.conv3.weight, layer3.3.bn3.weight, layer3.3.bn3.bias, layer3.3.bn3.running_mean, layer3.3.bn3.running_var, layer3.3.bn3.num_batches_tracked, layer3.4.conv1.weight, layer3.4.conv2.weight, layer3.4.bn1.weight, layer3.4.bn1.bias, layer3.4.bn1.running_mean, layer3.4.bn1.running_var, layer3.4.bn1.num_batches_tracked, layer3.4.bn2.weight, layer3.4.bn2.bias, layer3.4.bn2.running_mean, layer3.4.bn2.running_var, layer3.4.bn2.num_batches_tracked, layer3.4.conv3.weight, layer3.4.bn3.weight, layer3.4.bn3.bias, layer3.4.bn3.running_mean, layer3.4.bn3.running_var, layer3.4.bn3.num_batches_tracked, layer3.5.conv1.weight, layer3.5.conv2.weight, layer3.5.bn1.weight, layer3.5.bn1.bias, layer3.5.bn1.running_mean, layer3.5.bn1.running_var, layer3.5.bn1.num_batches_tracked, layer3.5.bn2.weight, layer3.5.bn2.bias, layer3.5.bn2.running_mean, layer3.5.bn2.running_var, layer3.5.bn2.num_batches_tracked, layer3.5.conv3.weight, layer3.5.bn3.weight, layer3.5.bn3.bias, layer3.5.bn3.running_mean, layer3.5.bn3.running_var, layer3.5.bn3.num_batches_tracked, layer4.0.conv1.weight, layer4.0.conv2.weight, layer4.0.bn1.weight, layer4.0.bn1.bias, layer4.0.bn1.running_mean, layer4.0.bn1.running_var, layer4.0.bn1.num_batches_tracked, layer4.0.bn2.weight, layer4.0.bn2.bias, layer4.0.bn2.running_mean, layer4.0.bn2.running_var, layer4.0.bn2.num_batches_tracked, layer4.0.conv3.weight, layer4.0.bn3.weight, layer4.0.bn3.bias, layer4.0.bn3.running_mean, layer4.0.bn3.running_var, layer4.0.bn3.num_batches_tracked, layer4.0.downsample.0.weight, layer4.0.downsample.1.weight, layer4.0.downsample.1.bias, layer4.0.downsample.1.running_mean, layer4.0.downsample.1.running_var, layer4.0.downsample.1.num_batches_tracked, layer4.1.conv1.weight, layer4.1.conv2.weight, layer4.1.bn1.weight, layer4.1.bn1.bias, layer4.1.bn1.running_mean, layer4.1.bn1.running_var, layer4.1.bn1.num_batches_tracked, layer4.1.bn2.weight, layer4.1.bn2.bias, layer4.1.bn2.running_mean, layer4.1.bn2.running_var, layer4.1.bn2.num_batches_tracked, layer4.1.conv3.weight, layer4.1.bn3.weight, layer4.1.bn3.bias, layer4.1.bn3.running_mean, layer4.1.bn3.running_var, layer4.1.bn3.num_batches_tracked, layer4.2.conv1.weight, layer4.2.conv2.weight, layer4.2.bn1.weight, layer4.2.bn1.bias, layer4.2.bn1.running_mean, layer4.2.bn1.running_var, layer4.2.bn1.num_batches_tracked, layer4.2.bn2.weight, layer4.2.bn2.bias, layer4.2.bn2.running_mean, layer4.2.bn2.running_var, layer4.2.bn2.num_batches_tracked, layer4.2.conv3.weight, layer4.2.bn3.weight, layer4.2.bn3.bias, layer4.2.bn3.running_mean, layer4.2.bn3.running_var, layer4.2.bn3.num_batches_tracked

missing keys in source state_dict: backbone.layer3.1.conv3.weight, backbone.layer2.1.bn2.bias, backbone.layer3.3.bn2.running_mean, backbone.layer1.2.conv3.weight, backbone.layer3.2.bn3.num_batches_tracked, backbone.layer3.4.bn3.weight, backbone.layer2.1.bn1.num_batches_tracked, backbone.layer3.2.bn3.running_mean, backbone.layer1.0.bn3.weight, backbone.layer2.3.conv1.weight, backbone.layer3.5.bn2.num_batches_tracked, backbone.bn1.num_batches_tracked, backbone.layer2.2.bn1.weight, backbone.layer4.0.downsample.1.weight, backbone.layer4.2.bn2.running_var, backbone.layer2.2.bn3.weight, backbone.layer3.4.bn1.weight, backbone.layer1.1.bn2.running_mean, backbone.layer3.2.bn1.weight, backbone.layer1.0.conv1.weight, backbone.layer3.0.bn2.num_batches_tracked, backbone.layer4.1.conv2.weight, backbone.layer2.3.bn2.running_mean, backbone.layer3.2.conv2.weight, backbone.layer3.0.downsample.1.num_batches_tracked, backbone.layer3.3.bn1.weight, backbone.layer1.0.bn2.running_var, backbone.layer3.5.bn2.bias, backbone.layer2.1.bn1.weight, backbone.layer1.2.bn2.num_batches_tracked, backbone.layer4.2.bn3.num_batches_tracked, backbone.layer3.3.conv3.weight, backbone.bn1.running_var, backbone.layer3.3.bn1.running_var, backbone.layer3.5.bn1.weight, backbone.layer4.1.bn2.running_mean, backbone.layer4.0.downsample.1.running_mean, backbone.layer4.1.bn1.running_var, backbone.layer3.0.bn3.running_var, backbone.layer3.0.downsample.1.running_mean, backbone.layer1.0.bn3.running_var, backbone.layer3.1.bn1.running_var, backbone.layer3.3.bn1.bias, backbone.layer1.2.bn1.num_batches_tracked, backbone.layer4.0.bn3.num_batches_tracked, backbone.layer4.1.bn1.bias, backbone.layer4.1.bn3.bias, backbone.layer2.2.conv3.weight, backbone.layer3.5.bn2.weight, backbone.layer4.0.bn2.running_mean, backbone.layer1.0.downsample.1.running_mean, backbone.layer1.1.conv2.weight, backbone.layer2.1.bn1.running_mean, backbone.layer2.3.bn2.running_var, backbone.layer4.0.bn1.weight, backbone.layer4.1.bn2.bias, backbone.layer3.2.conv3.weight, backbone.layer3.1.bn2.running_mean, backbone.layer3.2.bn1.running_var, backbone.layer2.0.downsample.1.running_var, backbone.layer2.0.bn3.running_var, backbone.layer3.0.downsample.1.weight, backbone.layer2.2.bn2.running_var, backbone.layer3.3.bn3.weight, backbone.layer1.2.bn3.running_mean, backbone.layer4.0.bn3.bias, backbone.layer4.0.downsample.1.running_var, backbone.layer3.4.bn1.bias, backbone.layer4.1.bn3.running_var, backbone.layer2.0.bn3.running_mean, backbone.layer2.0.bn2.bias, backbone.layer3.0.conv3.weight, backbone.layer3.5.conv2.weight, cls_head.fc_cls.weight, backbone.layer1.0.bn2.weight, backbone.layer2.0.downsample.1.bias, backbone.layer1.0.conv3.weight, backbone.layer3.0.conv1.weight, backbone.layer3.5.bn3.running_var, backbone.layer3.4.bn1.num_batches_tracked, backbone.layer3.1.bn3.num_batches_tracked, backbone.layer2.3.bn3.weight, backbone.layer3.5.bn2.running_mean, backbone.layer1.1.bn1.running_mean, backbone.layer2.0.conv1.weight, backbone.layer1.1.bn2.num_batches_tracked, backbone.layer2.0.bn3.bias, backbone.layer2.3.bn1.running_mean, backbone.layer2.2.bn1.running_mean, backbone.layer1.1.bn1.running_var, backbone.layer2.3.bn2.weight, backbone.layer3.5.conv1.weight, backbone.layer2.0.conv2.weight, backbone.layer1.0.downsample.1.running_var, backbone.layer4.0.conv2.weight, backbone.layer4.0.conv3.weight, backbone.layer4.1.conv1.weight, backbone.layer3.4.bn2.bias, backbone.layer4.2.conv1.weight, backbone.layer3.1.bn1.bias, backbone.layer2.2.bn2.weight, backbone.layer3.2.bn1.num_batches_tracked, backbone.bn1.weight, backbone.layer3.4.conv3.weight, backbone.layer2.2.bn1.bias, backbone.layer1.1.bn2.running_var, backbone.layer1.2.bn1.bias, backbone.layer3.1.bn2.num_batches_tracked, backbone.layer3.5.bn1.num_batches_tracked, backbone.layer4.0.bn2.num_batches_tracked, backbone.layer4.2.bn2.running_mean, backbone.layer1.1.bn1.weight, backbone.layer2.0.downsample.1.running_mean, backbone.layer2.2.bn3.running_var, backbone.layer3.0.bn1.num_batches_tracked, backbone.layer3.3.bn3.bias, backbone.layer3.3.bn3.running_mean, backbone.layer3.0.bn1.bias, backbone.layer2.0.bn2.running_var, backbone.layer2.3.conv3.weight, backbone.layer2.3.bn1.weight, backbone.layer3.1.bn3.bias, backbone.layer4.1.bn2.num_batches_tracked, backbone.layer3.4.bn3.num_batches_tracked, backbone.layer4.2.bn3.running_var, backbone.layer1.1.bn3.running_var, backbone.layer2.0.downsample.1.num_batches_tracked, backbone.layer1.1.bn3.num_batches_tracked, backbone.layer2.0.bn2.weight, backbone.layer3.0.bn2.running_mean, backbone.layer3.2.bn3.weight, backbone.layer2.3.bn1.bias, backbone.layer3.5.bn1.bias, backbone.layer4.1.bn2.running_var, backbone.layer4.2.conv2.weight, backbone.layer3.3.bn3.running_var, backbone.layer2.2.bn2.num_batches_tracked, backbone.layer1.1.bn2.bias, backbone.layer2.0.bn1.num_batches_tracked, backbone.layer4.0.bn1.running_var, backbone.layer2.0.bn1.bias, backbone.layer3.2.bn1.bias, backbone.layer2.2.conv2.weight, backbone.layer3.2.bn2.running_mean, backbone.layer3.4.bn1.running_mean, backbone.layer3.5.conv3.weight, backbone.layer3.2.bn3.bias, backbone.layer4.0.bn3.running_var, backbone.layer3.2.bn2.bias, backbone.layer1.1.conv1.weight, backbone.layer3.1.bn1.num_batches_tracked, backbone.layer2.1.bn2.weight, backbone.layer3.3.bn2.bias, backbone.layer1.2.bn1.running_mean, backbone.layer3.4.bn3.running_var, backbone.layer1.2.bn2.running_mean, backbone.layer3.5.bn3.weight, backbone.layer1.0.downsample.1.bias, backbone.layer1.0.bn2.num_batches_tracked, backbone.layer1.1.bn3.weight, backbone.layer3.1.bn2.running_var, backbone.layer3.3.bn2.running_var, backbone.layer3.5.bn1.running_var, backbone.layer2.1.bn2.running_mean, backbone.layer3.1.conv2.weight, backbone.layer2.0.bn3.num_batches_tracked, backbone.layer2.1.conv1.weight, backbone.layer3.4.bn2.num_batches_tracked, backbone.layer2.0.conv3.weight, backbone.layer2.1.bn3.bias, backbone.layer1.0.bn1.running_mean, backbone.layer2.2.bn1.num_batches_tracked, backbone.layer3.2.bn2.weight, backbone.layer2.3.bn3.running_mean, backbone.layer3.2.bn1.running_mean, backbone.layer4.0.conv1.weight, backbone.layer2.0.bn3.weight, backbone.layer3.5.bn3.running_mean, backbone.layer4.2.bn2.bias, backbone.layer1.0.bn1.weight, backbone.layer1.1.conv3.weight, backbone.layer2.3.conv2.weight, backbone.layer3.3.conv1.weight, backbone.layer4.1.bn2.weight, backbone.layer3.0.bn1.weight, backbone.layer3.4.bn2.weight, backbone.layer1.2.conv2.weight, backbone.layer1.0.bn1.running_var, backbone.layer4.1.conv3.weight, backbone.layer3.1.bn1.running_mean, backbone.layer1.0.downsample.0.weight, backbone.layer3.1.bn2.weight, backbone.layer2.3.bn1.running_var, backbone.layer3.4.bn3.bias, backbone.layer4.2.bn3.running_mean, backbone.layer2.1.bn3.num_batches_tracked, backbone.layer4.1.bn3.weight, backbone.layer3.4.conv2.weight, backbone.layer1.0.bn2.running_mean, backbone.layer1.2.bn2.running_var, backbone.layer3.0.bn2.weight, backbone.layer2.0.bn2.num_batches_tracked, backbone.layer3.3.bn3.num_batches_tracked, backbone.layer2.1.bn3.running_var, backbone.layer3.1.bn3.running_mean, backbone.layer2.3.bn3.bias, backbone.layer3.5.bn3.bias, backbone.layer2.1.bn2.num_batches_tracked, backbone.layer4.1.bn3.num_batches_tracked, backbone.layer1.2.conv1.weight, backbone.layer1.2.bn1.running_var, backbone.layer2.3.bn1.num_batches_tracked, backbone.layer1.0.bn2.bias, backbone.layer2.3.bn3.running_var, backbone.layer3.0.bn3.num_batches_tracked, backbone.layer2.1.bn3.running_mean, backbone.layer3.3.bn2.num_batches_tracked, backbone.layer4.2.bn3.weight, backbone.layer4.0.bn3.running_mean, backbone.layer3.4.bn2.running_mean, backbone.layer2.1.bn1.running_var, backbone.layer4.0.bn1.bias, backbone.layer3.4.bn1.running_var, backbone.layer3.4.bn3.running_mean, backbone.layer1.0.conv2.weight, backbone.layer3.0.bn3.bias, backbone.layer1.0.bn3.running_mean, backbone.layer3.0.downsample.0.weight, backbone.layer3.0.downsample.1.running_var, backbone.layer3.1.bn2.bias, backbone.layer2.2.bn3.num_batches_tracked, backbone.layer3.0.bn2.bias, backbone.layer1.1.bn1.num_batches_tracked, backbone.layer3.2.bn2.num_batches_tracked, backbone.layer4.0.bn2.running_var, backbone.layer4.2.bn1.num_batches_tracked, backbone.layer1.0.bn3.bias, backbone.layer3.0.conv2.weight, backbone.layer2.3.bn2.bias, backbone.layer3.3.bn1.num_batches_tracked, backbone.layer3.3.bn2.weight, backbone.layer4.1.bn1.running_mean, backbone.layer4.2.bn1.weight, backbone.layer4.1.bn1.weight, backbone.layer3.1.bn3.weight, backbone.layer3.0.bn1.running_var, backbone.layer4.2.bn2.num_batches_tracked, backbone.layer4.2.conv3.weight, backbone.layer4.2.bn3.bias, backbone.layer3.5.bn3.num_batches_tracked, backbone.bn1.bias, backbone.bn1.running_mean, backbone.layer4.0.bn3.weight, backbone.layer4.0.bn1.num_batches_tracked, backbone.layer2.2.bn1.running_var, backbone.layer3.3.conv2.weight, backbone.layer1.0.bn1.bias, backbone.layer3.1.bn1.weight, backbone.layer3.2.bn3.running_var, backbone.layer1.1.bn3.bias, backbone.layer1.2.bn3.bias, backbone.layer2.1.bn3.weight, backbone.layer4.0.bn2.weight, backbone.layer3.2.bn2.running_var, backbone.layer4.1.bn3.running_mean, backbone.layer2.2.bn2.bias, backbone.layer2.2.bn3.bias, backbone.layer1.2.bn3.running_var, backbone.layer2.3.bn3.num_batches_tracked, backbone.layer3.0.bn3.running_mean, backbone.layer3.4.bn2.running_var, backbone.layer1.0.downsample.1.num_batches_tracked, backbone.layer1.2.bn2.bias, backbone.layer4.1.bn1.num_batches_tracked, backbone.layer1.2.bn1.weight, backbone.layer4.0.downsample.1.bias, backbone.layer1.2.bn2.weight, backbone.layer1.0.bn1.num_batches_tracked, backbone.layer1.1.bn3.running_mean, backbone.layer2.0.bn1.running_mean, backbone.layer2.3.bn2.num_batches_tracked, backbone.layer1.1.bn2.weight, backbone.layer4.0.bn1.running_mean, backbone.layer2.1.conv3.weight, backbone.layer1.0.bn3.num_batches_tracked, backbone.layer1.0.downsample.1.weight, backbone.layer3.2.conv1.weight, cls_head.fc_cls.bias, backbone.layer2.1.conv2.weight, backbone.layer1.2.bn3.num_batches_tracked, backbone.layer2.0.bn1.running_var, backbone.layer2.1.bn2.running_var, backbone.layer3.5.bn1.running_mean, backbone.layer2.0.bn2.running_mean, backbone.layer4.0.downsample.1.num_batches_tracked, backbone.layer3.0.bn2.running_var, backbone.layer4.2.bn1.running_var, backbone.layer1.1.bn1.bias, backbone.layer2.2.bn2.running_mean, backbone.layer4.2.bn1.running_mean, backbone.layer4.2.bn1.bias, backbone.layer3.1.conv1.weight, backbone.layer3.0.downsample.1.bias, backbone.layer4.0.downsample.0.weight, backbone.layer3.5.bn2.running_var, backbone.layer2.2.conv1.weight, backbone.layer2.1.bn1.bias, backbone.layer2.0.downsample.0.weight, backbone.layer4.2.bn2.weight, backbone.layer1.2.bn3.weight, backbone.layer2.0.bn1.weight, backbone.layer2.0.downsample.1.weight, backbone.conv1.weight, backbone.layer3.0.bn1.running_mean, backbone.layer3.3.bn1.running_mean, backbone.layer3.1.bn3.running_var, backbone.layer3.4.conv1.weight, backbone.layer2.2.bn3.running_mean, backbone.layer4.0.bn2.bias, backbone.layer3.0.bn3.weight
```

Is the pertrained weight wrong? Thanks!

**Comment by HaiyiMei** [comment]
Plus, I found that the pretrained weight for i3d in Model zoo has no weight for full-connect layer("cls_head.fc_cls.weight", "cls_head.fc_cls.bias"). Can you release a new pretrained i3d model? I'd be appreciated that!

**Comment by zhaoyue-zephyrus** [comment]
Hi @HaiyiMei , sorry about replying late. The previous link is wrong. The new link has been updated and you can find details in https://github.com/open-mmlab/mmaction/commit/eb7ace3458df6d551b99a1026abee2b209376a6b. Please check.

Sorry again for the inconvenience and hope this fix will be helpful.
